### ISSUE TITLE
Checking of duplicated transactions twice

### ISSUE THREAD

**Issue by Dino-Nuggies** [AY2425S1-CS2103-F13-1/tp#139]
Not sure if its intentional but you checked for duplicated transaction twice before adding into the TransactionBook.
Once in the execute() method of AddCommand and another in TransactionBook.addTransaction().

**Comment by rollingpencil** [comment]
Hi @Dino-Nuggies, this is intentional as `TranscationBook.addTransaction()` is not just used by the `AddCommand` class but would also be used by storage when loading the data into the transaction book. The check in `AddCommand` is useful to provide tailored error messages due to duplication explicitly caused by the AddCommand too. Furthermore, having the duplication transaction check at both places ensures more checks are done to prevent duplicate transactions.
