### ISSUE TITLE
Issues concerning the ability to add duplicated transactions 

### ISSUE THREAD

**Issue by Dino-Nuggies** [AY2425S1-CS2103-F13-1/tp#199]
Uncertainty with whether transactions with duplicated field should able to be added into the transactionBook
- By default each transactions are unique to each other due to differing Ids

# Problems with yes
- This can be confusing to some users in the future when they might have accidentally added duplicates

# Problems with no
- It can be unnecessary to add such limit
- Additionally some people might want to be able to add duplicated transactions in very specific use cases

**Comment by SeeYangZhi** [comment]
I believe the current approach was implemented with https://github.com/AY2425S1-CS2103-F13-1/tp/issues/4 in mind and we should stick with the current approach.

> * Additionally some people might want to be able to add duplicated transactions in very specific use cases

We acknowledge that some users might have such use cases. For example, when helping to pay for a friend twice on the same day for the exact latte at Starbucks, we may use the command `addTxn 1 amt/2.50 desc/sean owes me for latte` twice.

However, we do not want forgetful users to have duplicate transactions. We believe that the trade-off to prevent such duplicate transactions would be more beneficial for the general users. 

Back to the specific use cases, we recommend users to tweak the `desc` if it happens on a diff occasion, for example:
`addTxn 1 amnt/2.50 desc/sean owes me for morning latte`
`addTxn 1 amnt/2.50 desc/sean owes me for tea break latte`

**Comment by rollingpencil** [comment]
Furthermore, even though, by default, the transactions are unique to each other due to differing IDs, the transaction ID is only used internally for referential integrity, and users would only be shown the content of the transactions instead. To avoid confusing the user when they see double transactions, we should define equality as the same content. As we are striving for a CLI friendly interaction, it would not make sense for the user to type the transaction ID too.
