### ISSUE TITLE
[PE-D][Tester C] Can add 2 persons with the same email, phone, and address

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#372]
In this app, I can add more than 1 people that has the same email, phone, and address.

If more than 1 people has the same email, phone, and address, it is very unlikely that they are different persons. Hence, allowing the app to accept those kind of input might cause confusion.

![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/eaca1a73-02e5-4f6e-9d6e-af9e1fd87878.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hazzle23/ped#2

**Comment by SeeYangZhi** [comment]
> In this app, I can add more than 1 people that has the same email, phone, and address.
> 
> If more than 1 people has the same email, phone, and address, it is very unlikely that they are different persons. Hence, allowing the app to accept those kind of input might cause confusion.

What the Tester C has described is an expected behaviour of SpleetWaise. See the following explanation:

Most address books and contact management systems use a combination of fields like name and phone number as primary identifiers for detecting duplicates rather than requiring an exact match across all fields (such as email, address, and name). This is because:

**Our current and future Main Identifiers** - Name and Phone Number: Most address books primarily use name and phone number to detect duplicates, as these fields are more likely to uniquely identify an individual. If two entries have the same name and number, they are likely the same person, which triggers duplicate detection. However, emails and addresses are not as reliable for deduplication since they are more commonly shared across entities or may have legitimate overlaps.

**Flexibility in Contact Information**: People often share addresses, especially in cases of family members, roommates, or business contacts at the same office location. They may even share an email in cases of shared accounts or generic emails (e.g., info@company.com). However, each contact may have different names, purposes, or identifiers, making it impractical to flag them as duplicates solely based on overlapping address or email fields.

**Uncommon Case of All Fields Matching**: It is rare and usually intentional if multiple entries share the same name, phone, email, and address. Address books are designed to allow such cases, trusting users to distinguish between them if needed, rather than imposing strict deduplication that might inadvertently merge unrelated contacts
