### ISSUE TITLE
[PE-D][Tester E] Track undone balance only button does not filter the list

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#427]
There was no information about `Track undone balance only` checkbox in the user guide.

I assumed that by checking the box, it will filter the transaction list. However, it did not filter.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/c6b6c308-13c6-4b0c-ac9a-1688843cdd6f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: winstonlimjy/ped#10

**Comment by GavinSin** [comment]
This is the expected behavior. "Track undone balance only" feature only affects the balance overview section, where the user know how much he owe and owed. A ticked "Track undone balance only" checkbox means the balance overview are calculated by summing up all undone transaction amount only. And I agree that such feature should be explained in user guide for clarity.

With that said, this feature has been removed due to issue #484 . Hence, no action to be done on our side.
