### ISSUE TITLE
[PE-D][Tester E] Date format in adding transaction is in the future

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#432]
I ran this command `addTxn 1 amt/99 desc/haha date/12122333` and it was accepted. 

Which means I can have someone in the future from the year `2333` owing me money. This contradicts with the description of your application where I am splitting shared cost, which from what I understand, the event has already occured.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/ea5f46fb-7fc8-429b-a558-e4ff78826677.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: winstonlimjy/ped#12

**Comment by SeeYangZhi** [comment]
While the event could have already occurred, in this case, allowing users to set any date –– including far-future dates like 2333 –– can be considered valid within the application as it supports tracking of transactions. Since users may use the app not only to log past expenses but also to set reminders for future financial commitments (the description for the transaction could be decided by a normal user to be more practical, such as, “Alex owes me 9000 dollars and will pay back in 30 years” instead of what was provided by the tester such as, "haha"), having unrestricted date inputs allows for diverse use cases.

We intend to allow such flexibility as the app can accommodate a broad range of scenarios, from immediate payments to long-term loans as transactions. However, it would be beneficial to add a validation warning or a prompt for users when they enter an unusually distant date, prompting them to confirm whether it is intentional. This will be considered in #362.
