### ISSUE TITLE
[PE-D][Tester E] FilterTxn and AddTxn has undesired outcome. Table did not update with the latest transaction.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#437]
Initially, i filter the transaction list to done by inputting this command `filterTxn status/Done` which showed me this.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/9a0259a6-7de9-425d-94ec-ceff0778a069.png)

Then I add a transaction but it did not show on the transaction list. `addTxn 1 amt/1 desc/lol`

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/aee43424-ef00-4605-a1fa-a089df5505db.png)

I had to `listTxn` to see the transaction.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/188f813c-63f2-4aa0-abdb-d6f203b54b5e.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: winstonlimjy/ped#13

**Comment by rollingpencil** [comment]
This is intended as adding a transaction should not mess with the current filter applied as they are independent components. Thus, as you stated, you have filtered by `Done` status, and since you added a new transaction without the `status/Done` prefix, it is considered by default as undone. Thus, it would not be shown in the currently applied filter.
